### ISSUE TITLE
Issues in packet_link_qualification.proto

### ISSUE THREAD

**Issue by romeyod** [openconfig/gnoi#71]
Hello

Few issues in [add packet_link_qualification] (https://github.com/openconfig/gnoi/commit/28e696d767f5ca950b6afd8f4bbd40263b3d0b76)

`uint16 packet_size = 1500;`

"uint16" is not a valid proto3 type.

[https://github.com/openconfig/gnoi/blob/28e696d767f5ca950b6afd8f4bbd40263b3d0b76/packet_link_qualification/packet_link_qualification.proto#L91](url)

Also, proto3 does not support default values right? The "= 1500" is not needed.

@[yushiyushi](https://github.com/openconfig/gnoi/commits?author=yushiyushi) @[marcushines](https://github.com/openconfig/gnoi/commits?author=marcushines)

**Comment by romeyod** [comment]
You will also need the below in the proto file so that `compile_protos.sh` is able to generate the dependencies.

`option go_package = "github.com/openconfig/gnoi/packet_link_qualification";`

**Comment by yushiyushi** [comment]
hi, i am sorry for causing the issue here,  I have added `packet_link_qualification` at `compile_protos.sh`, i thought `--go_opt=paths=source_relative $p/$p.proto` can find `https://github.com/openconfig/gnoi/blob/master/packet_link_qualification/packet_link_qualification.proto`
do i also have to add 

`option go_package = "github.com/openconfig/gnoi/packet_link_qualification"; 
` ?

**Comment by marcushines** [comment]
closing as v2 has been submitted
